# Generated by Django 3.0.3 on 2020-05-23 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apaan', '0002_auto_20200522_0129'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='created',
            new_name='create',
        ),
    ]
